import type { Location, UserProfile, Activity } from './types';

export const locations: Location[] = [
  {
    id: '1',
    name: 'Bunker del Carmel',
    description:
      'Panoramic views of the city from a historic anti-aircraft bunker.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'barcelona viewpoint',
    crowdLevel: 'high',
    position: { lat: 41.4165, lng: 2.1625 },
    tags: ['viewpoint', 'history', 'free'],
    isFeatured: true,
  },
  {
    id: '2',
    name: 'El Jardí Secret',
    description: 'A quiet, hidden garden cafe perfect for a relaxing afternoon.',
    category: 'gastronomy',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'garden cafe',
    crowdLevel: 'low',
    position: { lat: 41.3888, lng: 2.1654 },
    tags: ['cafe', 'garden', 'quiet'],
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Museu de la Xocolata',
    description:
      'A museum dedicated to the history of chocolate, with workshops and tastings.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'chocolate museum',
    crowdLevel: 'medium',
    position: { lat: 41.3861, lng: 2.1818 },
    tags: ['museum', 'food', 'family'],
    isFeatured: false,
  },
  {
    id: '4',
    name: 'Carrer de Blai',
    description: 'A lively street in Poble-sec famous for its many pinchos bars.',
    category: 'gastronomy',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 20,
    dataAiHint: 'tapas street',
    crowdLevel: 'high',
    position: { lat: 41.3734, lng: 2.1643 },
    tags: ['tapas', 'nightlife', 'foodie'],
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Parc del Laberint d\'Horta',
    description:
      'The oldest garden in Barcelona, featuring a beautiful hedge maze.',
    category: 'nature',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'hedge maze',
    crowdLevel: 'low',
    position: { lat: 41.441, lng: 2.1465 },
    tags: ['park', 'maze', 'romantic'],
    isFeatured: true,
  },
  {
    id: '6',
    name: 'Libreria Altaïr',
    description:
      'One of the largest travel bookshops in Europe, a haven for explorers.',
    category: 'shopping',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'bookstore interior',
    crowdLevel: 'medium',
    position: { lat: 41.3916, lng: 2.1668 },
    tags: ['books', 'travel', 'shopping'],
    isFeatured: true,
  },
];

const userActivities: Activity[] = [
  {
    id: 'act1',
    userId: 'user1',
    activityType: 'visit',
    date: '2023-05-10T15:00:00Z',
    detail: { id: '5', name: 'Parc del Laberint d\'Horta' },
    points: 15,
  },
  {
    id: 'act2',
    userId: 'user1',
    activityType: 'visit',
    date: '2023-05-12T11:00:00Z',
    detail: { id: '3', name: 'Museu de la Xocolata' },
    points: 10,
  },
];

export const user: UserProfile = {
  id: 'user1',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  avatarUrl: 'https://placehold.co/100x100.png',
  preferredLanguage: 'en',
  points: 125,
  level: 2,
  activityHistory: userActivities,
  registrationDate: '2023-01-15T09:30:00Z',
  preferences: {
    interests: 'parks, history, architecture',
    crowdTolerance: 'low',
    sustainabilityFocused: true,
  },
};
