import type { Location, UserProfile, Activity } from './types';

export const locations: Location[] = [
  // Classic Tourist Spots (often high crowd)
  {
    id: '1',
    name: 'Sagrada Família',
    description: 'Iconic basilica by Antoni Gaudí, a masterpiece of Catalan Modernisme.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'barcelona cathedral',
    crowdLevel: 'high',
    position: { lat: 41.4036, lng: 2.1744 },
    tags: ['gaudí', 'architecture', 'iconic'],
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Park Güell',
    description: 'Public park system composed of gardens and architectonic elements by Gaudí.',
    category: 'nature',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'barcelona park',
    crowdLevel: 'high',
    position: { lat: 41.4145, lng: 2.1527 },
    tags: ['gaudí', 'park', 'viewpoint'],
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Gothic Quarter (Barri Gòtic)',
    description: 'The historic center of the old city of Barcelona, with narrow medieval streets.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'gothic quarter',
    crowdLevel: 'high',
    position: { lat: 41.3831, lng: 2.1769 },
    tags: ['history', 'architecture', 'shopping'],
    isFeatured: false,
  },
  {
    id: '4',
    name: 'La Rambla',
    description: 'A famous tree-lined pedestrian street, bustling with tourists and street performers.',
    category: 'leisure',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'barcelona street',
    crowdLevel: 'high',
    position: { lat: 41.3813, lng: 2.1729 },
    tags: ['street', 'shopping', 'touristy'],
    isFeatured: false,
  },
  {
    id: '5',
    name: 'Mercat de Sant Josep de la Boqueria',
    description: 'Large public market with a diverse selection of goods, a foodie paradise.',
    category: 'gastronomy',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'food market',
    crowdLevel: 'high',
    position: { lat: 41.3817, lng: 2.1715 },
    tags: ['market', 'food', 'tapas'],
    isFeatured: false,
  },
  {
    id: '6',
    name: 'Casa Batlló',
    description: 'A building in the center of Barcelona, a masterpiece by Gaudí.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'gaudi building',
    crowdLevel: 'high',
    position: { lat: 41.3916, lng: 2.1650 },
    tags: ['gaudí', 'architecture', 'modernisme'],
    isFeatured: false,
  },
  {
    id: '7',
    name: 'Casa Milà (La Pedrera)',
    description: 'Another modernist building by Gaudí, with a famous rooftop terrace.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'gaudi architecture',
    crowdLevel: 'high',
    position: { lat: 41.3954, lng: 2.1618 },
    tags: ['gaudí', 'architecture', 'rooftop'],
    isFeatured: false,
  },
  {
    id: '8',
    name: 'Picasso Museum',
    description: 'Extensive collection of artworks by the 20th-century Spanish artist Pablo Picasso.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'art museum',
    crowdLevel: 'high',
    position: { lat: 41.3853, lng: 2.1810 },
    tags: ['museum', 'art', 'picasso'],
    isFeatured: false,
  },
  {
    id: '9',
    name: 'Montjuïc Castle',
    description: 'An old military fortress, with roots dating back from 1640, built on top of Montjuïc hill.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'castle barcelona',
    crowdLevel: 'medium',
    position: { lat: 41.3639, lng: 2.1658 },
    tags: ['castle', 'history', 'viewpoint'],
    isFeatured: false,
  },
  {
    id: '10',
    name: 'Magic Fountain of Montjuïc',
    description: 'Spectacular display of color, light, motion, music and water acrobatics.',
    category: 'leisure',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'magic fountain',
    crowdLevel: 'high',
    position: { lat: 41.3714, lng: 2.1517 },
    tags: ['show', 'free', 'nightlife'],
    isFeatured: false,
  },
  // Hidden Gems & Sustainable Spots (low to medium crowd)
  {
    id: '11',
    name: 'Bunker del Carmel',
    description: 'Panoramic views of the city from a historic anti-aircraft bunker.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'barcelona viewpoint',
    crowdLevel: 'medium',
    position: { lat: 41.4165, lng: 2.1625 },
    tags: ['viewpoint', 'history', 'free'],
    isFeatured: true,
  },
  {
    id: '12',
    name: 'El Jardí Secret',
    description: 'A quiet, hidden garden cafe perfect for a relaxing afternoon.',
    category: 'gastronomy',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 20,
    dataAiHint: 'garden cafe',
    crowdLevel: 'low',
    position: { lat: 41.3888, lng: 2.1654 },
    tags: ['cafe', 'garden', 'quiet'],
    isFeatured: true,
  },
  {
    id: '13',
    name: 'Parc del Laberint d\'Horta',
    description: 'The oldest garden in Barcelona, featuring a beautiful hedge maze.',
    category: 'nature',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'hedge maze',
    crowdLevel: 'low',
    position: { lat: 41.441, lng: 2.1465 },
    tags: ['park', 'maze', 'romantic'],
    isFeatured: true,
  },
  {
    id: '14',
    name: 'Carrer de Blai',
    description: 'A lively street in Poble-sec famous for its many pinchos bars.',
    category: 'gastronomy',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 20,
    dataAiHint: 'tapas street',
    crowdLevel: 'medium',
    position: { lat: 41.3734, lng: 2.1643 },
    tags: ['tapas', 'nightlife', 'foodie'],
    isFeatured: true,
  },
  {
    id: '15',
    name: 'Libreria Altaïr',
    description: 'One of the largest travel bookshops in Europe, a haven for explorers.',
    category: 'shopping',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'bookstore interior',
    crowdLevel: 'low',
    position: { lat: 41.3916, lng: 2.1668 },
    tags: ['books', 'travel', 'shopping'],
    isFeatured: true,
  },
  {
    id: '16',
    name: 'Monestir de Pedralbes',
    description: 'A beautiful Gothic monastery that offers a peaceful escape from the city.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'gothic monastery',
    crowdLevel: 'low',
    position: { lat: 41.3953, lng: 2.1158 },
    tags: ['history', 'quiet', 'architecture'],
    isFeatured: true,
  },
  {
    id: '17',
    name: 'Hospital de Sant Pau',
    description: 'A stunning complex of modernist buildings and a UNESCO World Heritage Site.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'modernist hospital',
    crowdLevel: 'medium',
    position: { lat: 41.4116, lng: 2.1746 },
    tags: ['architecture', 'modernisme', 'history'],
    isFeatured: true,
  },
  {
    id: '18',
    name: 'Gràcia Neighborhood',
    description: 'A bohemian neighborhood with independent shops, cozy squares, and a village-like atmosphere.',
    category: 'leisure',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'charming neighborhood',
    crowdLevel: 'medium',
    position: { lat: 41.4027, lng: 2.1565 },
    tags: ['neighborhood', 'bohemian', 'shopping'],
    isFeatured: false,
  },
  {
    id: '19',
    name: 'Plaça de Sant Felip Neri',
    description: 'A small, romantic, and hauntingly beautiful square in the Gothic Quarter.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'historic square',
    crowdLevel: 'low',
    position: { lat: 41.3833, lng: 2.1750 },
    tags: ['history', 'quiet', 'romantic'],
    isFeatured: true,
  },
  {
    id: '20',
    name: 'Barceloneta Beach',
    description: 'The city\'s most famous beach, offering sand, sun, and seafood restaurants.',
    category: 'nature',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 5,
    dataAiHint: 'barcelona beach',
    crowdLevel: 'high',
    position: { lat: 41.3792, lng: 2.1895 },
    tags: ['beach', 'summer', 'leisure'],
    isFeatured: false,
  },
  {
    id: '21',
    name: 'Museu Nacional d\'Art de Catalunya (MNAC)',
    description: 'Houses a vast collection of Catalan art, located in the stunning Palau Nacional.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'art museum facade',
    crowdLevel: 'medium',
    position: { lat: 41.3683, lng: 2.1534 },
    tags: ['art', 'museum', 'viewpoint'],
    isFeatured: false,
  },
  {
    id: '22',
    name: 'Tibidabo Amusement Park',
    description: 'A vintage amusement park on a mountain with spectacular views of Barcelona.',
    category: 'leisure',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'amusement park',
    crowdLevel: 'medium',
    position: { lat: 41.4220, lng: 2.1192 },
    tags: ['family', 'viewpoint', 'fun'],
    isFeatured: false,
  },
  {
    id: '23',
    name: 'Palau de la Música Catalana',
    description: 'A concert hall in the Modernista style, a UNESCO World Heritage Site.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'concert hall',
    crowdLevel: 'medium',
    position: { lat: 41.3875, lng: 2.1752 },
    tags: ['music', 'architecture', 'modernisme'],
    isFeatured: false,
  },
  {
    id: '24',
    name: 'El Born Centre de Cultura i Memòria',
    description: 'A former market building housing archaeological ruins from the 18th century.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'cultural center',
    crowdLevel: 'low',
    position: { lat: 41.3852, lng: 2.1827 },
    tags: ['history', 'museum', 'free'],
    isFeatured: true,
  },
  {
    id: '25',
    name: 'Parc de la Ciutadella',
    description: 'Barcelona\'s largest central park, with a zoo, a lake, and the Catalan Parliament.',
    category: 'nature',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'city park',
    crowdLevel: 'medium',
    position: { lat: 41.3881, lng: 2.1860 },
    tags: ['park', 'nature', 'family'],
    isFeatured: false,
  },
  {
    id: '26',
    name: 'Mercat de Santa Caterina',
    description: 'A vibrant market known for its wavy, colorful mosaic roof.',
    category: 'gastronomy',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'colorful market',
    crowdLevel: 'medium',
    position: { lat: 41.3860, lng: 2.1793 },
    tags: ['market', 'food', 'architecture'],
    isFeatured: true,
  },
  {
    id: '27',
    name: 'Fundació Joan Miró',
    description: 'A museum of modern art honoring Joan Miró, located on Montjuïc hill.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'modern art',
    crowdLevel: 'medium',
    position: { lat: 41.3687, lng: 2.1598 },
    tags: ['art', 'museum', 'miro'],
    isFeatured: false,
  },
  {
    id: '28',
    name: 'Carrer dels Tallers',
    description: 'A street known for its vintage clothing stores, record shops, and alternative vibe.',
    category: 'shopping',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 10,
    dataAiHint: 'vintage shops',
    crowdLevel: 'low',
    position: { lat: 41.3845, lng: 2.1678 },
    tags: ['shopping', 'vintage', 'music'],
    isFeatured: true,
  },
  {
    id: '29',
    name: 'Jardins de Mossèn Costa i Llobera',
    description: 'A specialized botanical garden on Montjuïc with a vast collection of cacti and succulents.',
    category: 'nature',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 15,
    dataAiHint: 'cactus garden',
    crowdLevel: 'low',
    position: { lat: 41.3664, lng: 2.1627 },
    tags: ['garden', 'plants', 'viewpoint'],
    isFeatured: true,
  },
  {
    id: '30',
    name: 'The Egg of Columbus (L\'Ou com Balla)',
    description: 'A peculiar tradition of making an egg "dance" on a fountain jet, found in several Gothic courtyards during Corpus Christi.',
    category: 'culture',
    imageUrl: 'https://placehold.co/600x400.png',
    points: 20,
    dataAiHint: 'dancing egg',
    crowdLevel: 'low',
    position: { lat: 41.3838, lng: 2.1764 },
    tags: ['tradition', 'quirky', 'free'],
    isFeatured: true,
  },
  ...Array.from({ length: 170 }, (_, i) => {
    const id = 31 + i;
    const lat = 41.3851 + (Math.random() - 0.5) * 0.1;
    const lng = 2.1734 + (Math.random() - 0.5) * 0.1;
    const crowdLevels: ('low' | 'medium' | 'high')[] = ['low', 'medium', 'high'];
    const categories: ('nature' | 'culture' | 'gastronomy' | 'shopping' | 'leisure')[] = ['nature', 'culture', 'gastronomy', 'shopping', 'leisure'];
    const names = [
        'Mercat del Ninot', 'CosmoCaixa', 'Poble Espanyol', 'Camp Nou', 'CaixaForum', 'CCCB', 'MACBA', 'Sant Pau Recinte Modernista',
        'Jardins de Laribal', 'Teatre Grec', 'Refugi 307', 'El Carmel Market', 'Can Framis Museum', 'Design Museum of Barcelona',
        'Maritime Museum', 'Chocolate Museum', 'Ideal Centre d\'Arts Digitals', 'Bogatell Beach', 'Mar Bella Beach',
        'Poblenou Cemetery', 'Torre Glòries', 'El Disseny Hub', 'Palo Alto Market', 'Two Schmucks Bar', 'Paradiso Bar',
        'Disfrutar Restaurant', 'Tickets Bar', 'Quimet & Quimet', 'El Xampanyet', 'Bar del Pla', 'Federal Cafe',
        'Satan\'s Coffee Corner', 'Nomad Coffee', 'Skatepark Mar Bella', 'Bunkers del Guinardó', 'Plaça del Sol', 'Plaça de la Virreina',
        'Carrer Verdi', 'Cines Verdi', 'Mercat de la Llibertat', 'Casa Vicens', 'Gaudí Experiència', 'Antic Teatre',
        'Jardins de Rubió i Lluch', 'Filmoteca de Catalunya', 'Mercat de Sant Antoni', 'Plaça d\'Espanya', 'Arenas de Barcelona',
        'Joan Miró Park', 'Parc de l\'Espanya Industrial', 'Sants Market', 'Hostafrancs Market', 'Collserola Tower',
        'Fabra Observatory', 'Walden 7', 'Can Mercader Park', 'Torre Bellesguard', 'Cosmocaixa', 'Museu Blau'
    ];
    const name = names[i % names.length] + (names.length < 170 ? ` ${Math.floor(i/names.length)}` : '');
    return {
      id: `${id}`,
      name: `${name}`,
      description: `A unique spot in Barcelona known for its ${categories[i % categories.length]}.`,
      category: categories[i % categories.length],
      imageUrl: 'https://placehold.co/600x400.png',
      points: 5 + (i % 3) * 5,
      dataAiHint: 'barcelona spot',
      crowdLevel: crowdLevels[i % crowdLevels.length],
      position: { lat, lng },
      tags: ['local', 'experience'],
      isFeatured: i % 10 === 0,
    };
  })
];

const userActivities: Activity[] = [
  {
    id: 'act1',
    userId: 'user1',
    activityType: 'visit',
    date: '2023-05-10T15:00:00Z',
    detail: { id: '13', name: 'Parc del Laberint d\'Horta' },
    points: 15,
  },
  {
    id: 'act2',
    userId: 'user1',
    activityType: 'visit',
    date: '2023-05-12T11:00:00Z',
    detail: { id: '5', name: 'Mercat de Sant Josep de la Boqueria' },
    points: 10,
  },
];

export const user: UserProfile = {
  id: 'user1',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  avatarUrl: 'https://placehold.co/100x100.png',
  preferredLanguage: 'es',
  points: 125,
  level: 2,
  activityHistory: userActivities,
  registrationDate: '2023-01-15T09:30:00Z',
  preferences: {
    interests: 'parks, history, architecture',
    crowdTolerance: 'low',
    sustainabilityFocused: true,
  },
};
